FROM alpine:3.2

ARG HAPROXY_MAJOR
ENV HAPROXY_MAJOR ${HAPROXY_MAJOR}
ARG HAPROXY_VERSION
ENV HAPROXY_VERSION ${HAPROXY_VERSION}
ARG WITH_LUA
ENV WITH_LUA ${WITH_LUA}

COPY build.sh /build.sh
RUN /build.sh

CMD [ "/usr/sbin/haproxy", "-f", "/etc/haproxy/haproxy.cfg", "-db" ]
