FROM alpine:3.2

ARG HAPROXY_MAJOR
ENV HAPROXY_MAJOR ${HAPROXY_MAJOR}
ARG HAPROXY_VERSION
ENV HAPROXY_VERSION ${HAPROXY_VERSION}

RUN apk update \
	&& apk upgrade \
	&& apk add haproxy \
	&& rm -rf /etc/haproxy/haproxy.cfg \
	&& rm -rf /var/cache/apk/*

CMD [ "/usr/sbin/haproxy", "-f", "/etc/haproxy/haproxy.cfg", "-db" ]
